---
title: "Modeling"
output:
  pdf_document: default
  html_notebook: default
header-includes:
  - \usepackage{caption}
---

```{r include = F}
# libraries
library(tidyverse)
library(lme4)
library(lattice)
library(gridExtra)
library(knitr)

# load data
nb <- readRDS("Data/nb.rds")

# visual options
theme_set(theme_bw())
```

\captionsetup[table]{labelformat = empty}

```{r}
# create model
mod_full <- aov(Glucose ~ (Gender+NutritionBar+Minutes)^2 + Error(Participant), data = nb)
tab_full <- summary(mod_full)
kable(tab_full$`Error: Participant`[[1]], caption = "Error: Participant")
kable(tab_full$`Error: Within`[[1]], caption = "Error: Within")
```

\newpage

\captionsetup[table]{labelformat = empty}

```{r}
# reduce model
mod_red <- aov(Glucose ~ NutritionBar*Minutes + Error(Participant), data = nb)
tab_red <- summary(mod_red)
kable(tab_red$`Error: Participant`[[1]], caption = "Error: Participant")
kable(tab_red$`Error: Within`[[1]], caption = "Error: Within")
```

```{r}
# create model/objects for residual plots
mod_plot <- lmer(Glucose ~ NutritionBar*Minutes + (1 | NutritionBar:Participant), data = nb)
mod_resid <- resid(mod_plot)
mod_fitted <- fitted(mod_plot)
nb1 <- nb %>% mutate(res = mod_resid,
                     index = 1:n())

# generate plots
r1 <- plot(mod_plot, xlab = "Fitted Values", ylab = "Residuals", pch = 19, col = "black")
r2 <- qqmath(mod_plot, pch = 19, col = "black")
r3 <- ggplot(nb1, aes(res)) +
  geom_histogram(binwidth = 1) +
  xlab("Residuals") +
  ylab("Count")
r4 <- ggplot(nb1, aes(index, res)) +
  geom_point() +
  geom_line() +
  xlab("Order") +
  ylab("Residuals")
grid.arrange(r1, r2, r3, r4, nrow = 2)

# save model
saveRDS(mod_plot, "reduced_model.RDS")

# residual checks
# resid_test <- nb$Glucose - mod_fitted
# round(mod_resid, 3) == round(resid_test, 3)
```


